name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --target-list="arm-softmmu" --enable-fdt --disable-vnc --disable-kvm --prefix=$(pwd)/release
    - name: make
      run: make
    - name: make check
      run: make check
